export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOAD_BUILDING = "LOAD_BUILDING";
export const REMOVE_BUILDING = "REMOVE_BUILDING";
export const LOAD_PRICES = "LOAD_PRICES";
export const REMOVE_PRICES = "REMOVE_PRICES";
